### ISSUE TITLE
Android App Crashes

### ISSUE THREAD

**Issue by ehutchllew** [localz/react-native-pinch#26]
Hey everyone, I've followed the instructions in the README, and have the iOS version working; however, every time I try to login via the Android app it just crashes without any error log. Has anyone encountered a similar issue or does anyone know the cause of this?

**Comment by arthurzoubin** [comment]
Yes, i also get the crash without and log.
I use react-native 0.48.3

**Comment by DazChong** [comment]
`adb logcat` shows:

```
12-20 15:37:34.656 18412 18801 E AndroidRuntime: Caused by: com.facebook.react.bridge.NoSuchKeyException: couldn't find key cert in dynamic object
12-20 15:37:34.656 18412 18801 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
12-20 15:37:34.656 18412 18801 E AndroidRuntime: 	at com.localz.RNPinch$FetchTask.doInBackground(RNPinch.java:101)
12-20 15:37:34.656 18412 18801 E AndroidRuntime: 	at com.localz.RNPinch$FetchTask.doInBackground(RNPinch.java:75)
```
Anyone know how to fix it?

**Comment by DazChong** [comment]
Thanks to @unloqer-io for his fork to fix the issue [https://github.com/unloqer-io/react-native-pinch/commit/0f0b4d464b937b882f823dcb2887e293d77d5afd](https://github.com/unloqer-io/react-native-pinch/commit/0f0b4d464b937b882f823dcb2887e293d77d5afd).
